SET cte_max_recursion_depth = 1000000;
SET @N = 2;

WITH RECURSIVE CALCULATE_PRIME AS (
    SELECT @N AS NUM, 0 AS ISNOTPRIME, @N - 1 AS DIVISOR, @N as CURR_NUM
    UNION ALL
    SELECT
        CASE WHEN DIVISOR != 0 THEN NUM ELSE CURR_NUM + 1 END AS NUM,
        CASE WHEN (DIVISOR NOT IN (1, NUM, 0)) AND (NUM % DIVISOR = 0) THEN 1 ELSE 0 END AS ISNOTPRIME,
        CASE WHEN DIVISOR !=0 THEN DIVISOR - 1 ELSE CURR_NUM END AS DIVISOR,
        CASE WHEN DIVISOR != 0 THEN CURR_NUM ELSE CURR_NUM + 1 END AS CURR_NUM
    FROM CALCULATE_PRIME
    WHERE NUM != 1001
), GET_ALL_PRIMES AS (
    SELECT NUM FROM CALCULATE_PRIME
        GROUP BY NUM
    HAVING SUM(ISNOTPRIME) = 0 AND NUM != 1001
)

SELECT GROUP_CONCAT(NUM SEPARATOR '&') AS concatenated_row FROM GET_ALL_PRIMES;
